### ISSUE TITLE
There is already support for completion builtin within yagna

### ISSUE THREAD

**Issue by tworec** [krunch3r76/gc__enhanced_completion#1]
![yagna-completion](https://user-images.githubusercontent.com/12720209/135310554-86e328e0-39cc-4e35-9836-6cede51563a9.gif)

**Comment by tworec** [comment]
I'm also enabling it for `golemsp`
https://github.com/golemfactory/yagna/pull/1617

**Comment by krunch3r76** [comment]
excellent, thanks for this! i will now see if i can add the contextual help menu to work with the built in support for tab completions!

**Comment by krunch3r76** [comment]
gc__bash_completion now interfaces with yagna's in-house completion script and aims to maintain compatibility.🙂
