### ISSUE TITLE
There is alredy pre-rel with completion support for golemsp

### ISSUE THREAD

**Issue by tworec** [krunch3r76/gc__enhanced_completion#2]
You can try it out via
 ```
curl -sSf https://join.golem.network/as-provider | YA_INSTALLER_CORE=pre-rel-v0.8.0-rc6 bash -
```
![golemsp_completion_demo](https://user-images.githubusercontent.com/12720209/135675678-104b898c-c661-4b68-a75f-0487e4ef85a1.gif)

**Comment by krunch3r76** [comment]
thanks so much tworec for your detailed input and for keeping me informed! i can easily add logic to anticipate it now!


respectfully --krunch3r

**Comment by krunch3r76** [comment]
added logic to support when golemsp executable can export completions. thanks again!

**Comment by tworec** [comment]
It is not officially released https://github.com/golemfactory/yagna/releases/tag/v0.8.0

**Comment by krunch3r76** [comment]
ah, ok, that is something i will keep an eye on. thanks!
